---
- name: creating user
  hosts: all 
  become: true
  # gather_facts: no
  # vars:
  # user_name: modi 
  vars_files: 
      - /home/ansadmin/playbooks/user.yml

  tasks:
  - name: creating user {{ user_name }}
    user:
      name: "{{ user_name }}"

  - name: creating a directory
    file:
      path: /opt/{{ user_name }}_tem_dir
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0755
