---
- name: creating a directory
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: create a dir1
    file:
      path: /opt/dir1
      state: directory
      mode: 0755
      owner: ansadmin
