---
- name: installing packages
  hosts: all 
  become: true
  gather_facts: no

  tasks:
  - name: installing packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - git
      - wget
      - tree
      - telnet
      - make
      - gzip
      
