---
- name: removing packages
  hosts: all
  become: true
  # gather_facts: no 

  tasks:
  - name: removing httpd redhat
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

  - name: removing httpd on ubuntu
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
