---
- name: playbook to install apache tomcat
  hosts: webservers
  become: true
  gather_facts: yes

  tasks:
  - name: installing java-1.8*
    yum:
      name: java
      state: installed

  - name: downloading tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.75/bin/apache-tomcat-8.5.75.tar.gz
      dest: /opt
      mode: 0755

  - name: extract packages
    unarchive: 
      src: /opt/apache-tomcat-8.5.75.tar.gz
      dest: /opt
      remote_src: yes

  - name: change permissions on apache-tomcatfile
    file: 
      path: /opt/apache-tomcat-8.5.75
      mode: 0755
      recurse: yes

  - name: creating link file for tomcat startup.sh
    file:
      src: /opt/apache-tomcat-8.5.75/bin
      dest: /usr/local/bin/tomcatup
      state: link

  - name: creating link file for tomcat shutdown.sh
    file:
      src: /opt/apache-tomcat-8.5.75/bin
      dest: /usr/local/bin/tomcatdown
      state: link

  - name: start the services
    command: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.75/bin
